import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  const { children } = props;

  console.log('props:', props);

  return (
    <html lang="zh-CN">
      <body className={inter.className}>
        <AntdRegistry>
        {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
